### PR TITLE
setup script

### PR DESCRIPTION
**Pull request by TrejGun**
Hi there!
I was tried to setup your project and found out docs are a bit tangled, so here are some changes to make it more easy

Hope you will find this usefull

### CODE REVIEW

**Comment by mogill** [comment]
Hi Trej!

Thanks so much for the npm/travis help -- obviously that stuff is not my forte.  I much prefer to spend time on the cache coherency, memory controller, and OS aspects of EMS; some parts don't get as much attention as they deserve.

I used almost everything in your commit but I also changed EMS' defaults so root permission wasn't required to run any tests or examples, and I was able to remove the sudo's everywhere.

Please note I checked in an important bug fix today, so you'll definitely want to pull.  Thanks again for your help, it's valuable time-saving and clue-giving -- greatly appreciated.

                    -J

**Comment by TrejGun** [comment]
Hi Jace

i'm happy i was able to help with your project

i have checked what exactly you merged and have a suggestion
[Install via GitHub](https://github.com/SyntheticSemantics/ems#install-via-github) sections still says

```
cd Examples/
mkdir -p node_modules
cd node_modules/
ln -s ../.. ems
cd ../
```

but you don't need to have a link to the root dir because 
```
sudo npm link ../ems
```
is almost same as
```
npm install -g ems
```
so `ems` will be available in `Examples`

**Comment by TrejGun** [comment]
@mogill, guess you missed last comment)

**Comment by mogill** [comment]
Sorry I didn't reply sooner, while I once worked on EMS full-time, I'm only able to work on it part-time now.

I left that blurb in there mostly for my reference -- I avoid installing EMS globally because as a developer I've had compilation fail and npm silently reverts to using the wrong version of EMS.

I have removed that section since as you note, it's redundant and mainly applies to me, but I did not yet commit it because I have also been updating other README sections and running benchmarks (nice speedups since two years ago).  I'm hoping to work in it some more tonight.

Thanks for being patient when I can't get around to simple things quickly.

**Comment by mogill** [comment]
Today I finally got around to finishing the README cleanup with new benchmarking -- all your stuff got in there.

My next task is to finish the OOP API, then use that to implement the Python API.  I really appreciate your continued help pointing out when things go astray.

**Pull request merged**
