### PR TITLE
Load images from README's own repo

### PR DESCRIPTION
**Pull request by mk-pmb**
<del>Next step would be to rename `Docs` to `docs` so we can host them on github.io.</del>
Actually, we could just as well use the entire master branch as the Github Pages root<del> and just put a redirecting `index.html`</del>.
Preview: https://mk-pmb.github.io/extended_memory_semantics/Docs/

### CODE REVIEW

**Comment by mogill** [comment]
Thanks for your tips: I added an `index.html` to redirect to the `Docs` directory and enabled the pages feature.  http://syntheticsemantics.github.io/ems/Docs/index.html is now functioning.

**Comment by mogill** [comment]
@mk-pmb I just realized when viewed from npm the image links are broken.  Is it bad style to hard-code URLs like https://raw.githubusercontent.com/SyntheticSemantics/ems/master/Docs/ccab.png?

**Comment by mk-pmb** [comment]
I'd remove the `index.html` so the readme will become the default page, and update the Website + Docs link at top of the readme.
If the images are published to npm, I'd consider that an npm bug. If they're not on npm, I'd use the github pages URL rather than the raw content API.

**Comment by mk-pmb** [comment]
PS for any watchers via email: I edited my first post and marked my suggestion to use a redirect as deleted when I realized GHP can use the Readme as default page.

**Comment by mogill** [comment]
I tried this, but it turns out GH formats the HTML embedded in MD, but the GHP site does not, so parts of the README are mangled on GHP.  I restored the index.html so the only place you can read the markdown is GH.  I also realized we forgot to update the `Examples/README`, so I fixed that.

**Pull request merged**
